---
title: "Assignment #5"
author: "YOUR FULL NAME"
format:
  html:
    toc: true
    number-sections: true
    embed-resources: true
---

# Assignment details  
In class, we wrangled and cleaned yield monitor data from a field in 2017.  

Now, you are asked to perform the same wrangling and cleaning steps on yield monitor data from the same field but collected in 2019 and 2020.  

These data sets need to be downloaded from the course GitHub page. They are located in the `03_data` as csv files (`03_yield19.csv` and `04_yield20.csv`). Copy them from the downloaded GitHub folder and paste into your `data` folder of project `07_yieldmonitor`.  

As part of the assignment, you will need to:  
- Wrangle and clean each of the two data sets  
- Provide me with a statistical summary of the cleaned version (including min, mean, max, sd, cv) to be included in the answers portion of this document (below).    
- Export the cleaned version to file (save it to the `data` folder of your `07_yieldmonitor` project).    

Some tips:  
- You can duplicate the wrangling and editing scripts we developed in class, renaming each of the copies to something like `yield19_wrangling.qmd` and `yield19_editor.qmd` for the 2019 data as an example. You can do the same for the 2020 data too.      

- Use these copied scripts as a template to adapt for each of the new data sets.  

- The Dry_Yield and Speed columns are not named the same in these two new data sets, you will need to accommodate this in your code.  

- Deadline is Monday Feb 23th 11:59 pm (we will use all 3 cleaned yield data on our next class period). 

# Questions  

## 1. What is the min, mean, max, and cv for the **cleaned** yield data from 2019?  

## 2. Create a map of the **cleaned** yield data from 2019, including the map elements of north arrow and scale, and coloring points according to yield using a colorblind-friendly color scale.  


## 3. What is the min, mean, max, and cv for the **cleaned** yield data from 2020?  

## 4. Create a map of the **cleaned** yield data from 2020, including the map elements of north arrow and scale, and coloring points according to yield using a colorblind-friendly color scale.  
 

---

After answering all questions, include your last name on the file name (e.g., A5-questions-Bastos.qmd), render it, and submit the .html on eLC by **Monday, Feb 23th 11:59 pm**.  
